services:
  ngnix:
    image: nginx:stable-alpine
    volumes:
      - /app/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - nginx-network
  

  api:
    image: landscape.api
    build:
      context: ./Landscape/src/Landscape.API
      dockerfile: Landscape.API/Dockerfile
    expose:
      - "8080"
    networks:
      - nginx-network

  landscape.db:
    image: postgres:latest
    container_name: Landscape.Db
    environment:
      - POSTGRES_DB=landscape
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./Landscape/src/Landscape.API/Landscape.API/containers/database:/var/lib/postgresql/Data
    ports:
      - "5432:5432"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
