services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - /app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - nginx-network

  api:
    image: IMAGE_PLACEHOLDER  # This gets replaced by the actual image tag via your CI/CD pipeline.
    expose:
      - "8080"
    networks:
      - nginx-network

  landscape.db:
    image: postgres:latest
    container_name: Landscape.Db
    environment:
      - POSTGRES_DB=landscape
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
