name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env:
  IMAGE_REPO: ${{ secrets.USERNAME }}/landscape.api
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CONTAINER_NAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build & Push API Image (Dev)
        uses: docker/build-push-action@v4
        with:
          context: ./src/Landscape.API
          file: ./src/Landscape.API/Landscape.API/Dockerfile
          push: true
          tags: ${{ secrets.CONTAINER_NAME }}/${{ secrets.USERNAME }}/landscape.api:latest

      - name: Replace image placeholder in docker-compose.prod file
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ secrets.CONTAINER_NAME }}/${{ secrets.USERNAME }}/landscape.api:latest|g" docker-compose.stage.yml

      - name: Copy docker-compose file to Droplet
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "docker-compose.stage.yml"
          target: "/app"

      - name: Copy nginx directory to Droplet
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "nginx/"
          target: "/app"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            if ! command -v doctl &> /dev/null; then
              echo "doctl not found, installing..."
              curl -sL https://github.com/digitalocean/doctl/releases/download/v1.70.0/doctl-1.70.0-linux-amd64.tar.gz | tar -xzv
              sudo mv doctl /usr/local/bin
            fi
            doctl auth init -t "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"
            doctl registry login --expiry-seconds 600
            cd /app
            docker-compose -f docker-compose.stage.yml pull
            docker-compose -f docker-compose.stage.yml up -d --remove-orphans
