name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CONTAINER_NAME }}   # e.g., registry.digitalocean.com/your-registry
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build & Push API Image
        uses: docker/build-push-action@v4
        with:
          context: ./src/Landscape.API
          file: ./src/Landscape.API/Landscape.API/Dockerfile
          push: true
          tags: ${{ secrets.CONTAINER_NAME }}/${{ secrets.USERNAME }}/landscape.api:latest

      - name: Replace image placeholder in docker-compose file
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ secrets.CONTAINER_NAME }}/${{ secrets.USERNAME }}/landscape.api:latest|g" docker-compose.yml

      - name: Copy docker-compose file to Droplet
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "docker-compose.yml"
          target: "/app/docker-compose.yml"

      - name: Copy nginx directory to Droplet
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "nginx/"
          target: "/app/nginx/"

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /app
            docker-compose pull
            docker-compose up -d --remove-orphans
